Fatal error: exception Failure("Continue statement not in loop")
